### ISSUE TITLE
Develop and API for customisation of Bars Style

### ISSUE THREAD

**Issue by hasnentai** [GeekyAnts/geekyants_flutter_charts#5]
```[tasklist]
### Tasks for Bar and Axis Styles
- [x] `BackgroundColour` for bars (gradient included)
- [x] `BorderColor` for bars.
- [x] `Borderwidth` for bars
- [x] `BorderRadius` for bars
- [x] `X` and `Y` Axis border width
- [x] `BarThickness` for bars
- [x] `hoverBackgroundColor` for bars
- [x] `hoverBorderColor` for bars
```
